spring:
  application:
    name: itoken-service-posts
  datasource:
    druid:
      url: jdbc:mysql://39.106.63.182:3307/itoken-service-posts?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: bInBin%19712345
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8504