spring:
  boot:
    admin:
      client:
        url: http://10.0.2.27:8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info