spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.62.134
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/